development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: testH_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: testH_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: testH_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock